// import { Navbar } from "./user/navbar";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <Navbar />
//         <div className="md:mt-16">{children}</div>
//       </body>
//     </html>
//   );
// }
// /app/(user)/layout.tsx
// import { Navbar } from "./user/navbar";
// import { Provider } from 'react-redux'; // Import Provider
// import store from '../(store)/store'; // Import your Redux store

// export default function UserLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <Provider store={store}> {/* Wrap with Redux Provider */}
//           <Navbar />
//           <div className="md:mt-16">{children}</div>
//         </Provider>
//       </body>
//     </html>
//   );
// }
import { Navbar } from "./user/navbar";
import ClientWrapper from '../(root)/ClientWrapper'; // Import your Client Wrapper

export default function UserLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientWrapper> {/* Wrap with ClientWrapper */}
          <Navbar />
          <div className="md:mt-16">{children}</div>
        </ClientWrapper>
      </body>
    </html>
  );
}
